language: ruby
rvm:
  - 2.3.0
postgres:
  adapter: postgresql
  database: jeanie-auth
  username: postgres
before_script:
  - "psql -c 'create database jeanie_auth;' -U postgres"
  - "rake db:migrate"