# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  database: <%= JSON.parse(ENV['VCAP_SERVICES'])['jeanieauthdb'].first['credentials']['database'] rescue 'jeanie-auth' %>
  username: <%= JSON.parse(ENV['VCAP_SERVICES'])['jeanieauthdb'].first['credentials']['username'] rescue '' %>
  password: <%= JSON.parse(ENV['VCAP_SERVICES'])['jeanieauthdb'].first['credentials']['password'] rescue '' %>
  host: <%= JSON.parse(ENV['VCAP_SERVICES'])['jeanieauthdb'].first['credentials']['hostname'] rescue 'localhost' %>
  encoding: UTF8
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: <%= JSON.parse(ENV['VCAP_SERVICES'])['jeanieauthdb'].first['credentials']['database'] rescue 'jeanie-auth' %>
  username: <%= JSON.parse(ENV['VCAP_SERVICES'])['jeanieauthdb'].first['credentials']['username'] rescue '' %>
  password: <%= JSON.parse(ENV['VCAP_SERVICES'])['jeanieauthdb'].first['credentials']['password'] rescue '' %>
  host: <%= JSON.parse(ENV['VCAP_SERVICES'])['jeanieauthdb'].first['credentials']['hostname'] rescue 'localhost' %>
  encoding: UTF8
  pool: 5
  timeout: 5000

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  database: <%= JSON.parse(ENV['VCAP_SERVICES'])['jeanieauthdb'].first['credentials']['database'] rescue 'jeanie_auth' %>
  username: <%= JSON.parse(ENV['VCAP_SERVICES'])['jeanieauthdb'].first['credentials']['username'] rescue 'postgres' %>
  password: <%= JSON.parse(ENV['VCAP_SERVICES'])['jeanieauthdb'].first['credentials']['password'] rescue '' %>
  host: <%= JSON.parse(ENV['VCAP_SERVICES'])['jeanieauthdb'].first['credentials']['hostname'] rescue 'localhost' %>
  encoding: UTF8
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: db/production.sqlite3
